@startuml
() eth
[zos]
eth -up- zos
note left of zos
bridge takes same mac address as eth
(ipv6 is enabled on the bridge)
- net.ipv6.conf.zos.disable_ipv6 = 0
end note
note left of eth
disable ipv6 on interface:
(ipv6 is disabled on the nic)
- net.ipv6.conf.<eth>.disable_ipv6 = 1
- net.ipv6.conf.all.forwarding = 0
end note
@enduml
