@startuml
actor Client as cl
participant RMB as rmb
participant Node as zos

cl --> rmb: Create an RMB message \n(cmd: zos.deployment.deploy, dat: base64(json(deployment)))
rmb -> zos: Decode payload(dat). \nSo node receive a deployment object
zos -> zos: Verify hash against contract hash\nVerify signature of the twin
zos -> rmb: Accepted Or Error
rmb --> cl: Response from the node
group If valid
zos -> zos: Deploy
end group
...
cl --> rmb: Get Deployment (cmd: zos.deployment.get)
rmb -> zos: Call get method
zos -> rmb: Get Response
rmb --> cl: Response
@enduml
