// Code generated by go-openrpc. DO NOT EDIT.
package zos_rpc

type GoOpenRPCService interface {
	// get system version
	SystemVersion() (*SystemVersionResult, error)
}
type Version struct {
	Zos string `json:"zos"`

	Zinit string `json:"zinit"`
}
type SystemVersionResult struct {
	// zos and zinit version on the node
	Version
}
