@startuml
title Provisioning a workload on the TFGrid

autonumber
actor "User" as user
actor "Farmer" as farmer
database "TF Explorer" as explorer
database Blockchain as blockchain
boundary Node as node

== Price definition ==
farmer -> explorer: Farmer set the price of its Resource units
== Resource research ==
user -> explorer: User look where to reserve some capacity
user <- explorer: Gives detail about the farmer owning the node selected
== Capacity pool creation  ==
user -> explorer: create a new capacity pool
explorer -> user: return a list of transaction to execute on the blockchain
== Capacity pool payment  ==
user -> blockchain: execute transactions
explorer <-> blockchain: verify transactions are done
blockchain -> farmer: forward the payed token to the farmer account
explorer -> explorer: fund the capacity pool
== Workload provisioning  ==
user -> explorer: sends workload definition
node <-> explorer: read workload definition
node -> node: provision workload
node -> explorer: write result of the provisining
explorer -> explorer: attached active workload to the capacity pool
user <- explorer: read the connection information to his workloa
== Resource monitoring ==
user <-> node: use / monitor workload
@enduml