@startuml
title Provisioning a workload on the TFGrid

autonumber
actor "User 3Bot" as user
actor "Farmer 3Bot" as farmer
database "TF Directory" as directory
database TFChain as tfchain
database BCDB as bcdb
boundary Node as node

== Resource research ==
user -> directory: User look where to deploy the workload
activate directory
user <- directory: Gives detail about the farmer owning the node selected
deactivate directory
== Price negotiation ==
user -> farmer: Start negotiation
activate farmer
farmer <-> user: negotiate prices
deactivate farmer
== Resource reservation  ==
user -> tfchain: lock some TFT
user -> bcdb: write description of the workload
activate node
== Resource provisioning  ==
node -> bcdb: read description of the workload
node -> node: provision workload
node -> bcdb: write result of the provisining
user <- bcdb: read the connection information to his workload
deactivate node
tfchain -> farmer: TFT are unlock progresively to the farmer
== Resource monitoring ==
user <-> node: use / monitor workload
@enduml