@startuml
package "Farm" {
    () "metrics" as m1
    () "metrics" as m2
    [Node 1] as n1
    [Node 2] as n2

    m1 - n1
    m2 - n2

    () "Data" as data
    m1 ..> data: poll
    m2 ..> data: poll
    database "Prometheus" as db
    data -down-> db

    folder "Grafana" {
        db -> [Dashboard]
    }
}
@enduml
