package main

import (
	"encoding/json"
	"net"
	"time"
)

type ZosRpcApi interface {
	SystemVersion() (Version, error)
	SystemDmi() (DMI, error)
	SystemHypervisor() (string, error)
	SystemDiagnostics() (Diagnostics, error)

	StorageMetrics() ([]PoolMetrics, error)

	Statistics() (Counters, error)

	PerfGet() (TaskResult, error)
	PerfGetAll() ([]TaskResult, error)

	NetworkPrivateIps(networkName string) ([]string, error)
	NetworkPublicIps() ([]string, error)
	NetworkHasIpv6() (bool, error)
	NetworkInterface() ([]net.IP, error)
	NetworkPublicConfig() ([]PublicConfig, error)
	NetworkWGPorts() ([]uint, error)

	GpuList() ([]GPUInfo, error)

	DeploymentChanges(contractId uint64) ([]Workload, error)
	DeploymentList() ([]Deployment, error)
	DeploymentGet(contractId uint64) (Deployment, error)
	DeploymentUpdate(deployment Deployment) error
	DeploymentCreate(deployment Deployment) error

	AdminPublicNICSet(iface string) error
	AdminPublicNICGet() (ExitDevice, error)
	AdminInterfaces() ([]Interface, error)
}

type Version struct {
	Zinit string
	Zos   string
}

type DMI struct {
	Tooling  Tooling
	Sections []Section
}

type Tooling struct {
	Aggregator string
	Decoder    string
}

type PropertyData struct {
	Val   string
	Items []string
}

type Section struct {
	HandleLine  string
	TypeStr     string
	Type        int
	SubSections []SubSection
}

type SubSection struct {
	Title      string
	Properties map[string]PropertyData
}

type ModuleStatus struct {
	Status Status
	Err    error
}

type Diagnostics struct {
	SystemStatusOk bool
	ZosModules     map[string]ModuleStatus
	Healthy        bool
}

type ObjectID struct {
	Name    string
	Version Version
}

type WorkerStatus struct {
	State     string
	StartTime time.Time
	Action    string
}

type Status struct {
	Objects []ObjectID
	Workers []WorkerStatus
}

type PoolMetrics struct {
	Name string
	Type string
	Size uint64
	Used uint64
}

type Counters struct {
	Total  Capacity
	Used   Capacity
	System Capacity
	Users  UsersCounters
}

type Capacity struct {
	CRU   uint64
	SRU   uint64
	HRU   uint64
	MRU   uint64
	IPV4U uint64
}

type UsersCounters struct {
	Deployments             int
	Workloads               int
	LastDeploymentTimestamp int64
}

type TaskResult struct {
	Name        string
	Description string
	Timestamp   uint64
	Result      interface{}
}

type PublicConfig struct {
	// Type define if we need to use
	// the Vlan field or the MacVlan
	Type string `json:"type"`
	// Vlan int16     `json:"vlan"`
	// Macvlan net.HardwareAddr

	IPv4 net.IPNet `json:"ipv4"`
	IPv6 net.IPNet `json:"ipv6"`

	GW4 net.IP `json:"gw4"`
	GW6 net.IP `json:"gw6"`

	// Domain is the node domain name like gent01.devnet.grid.tf
	// or similar
	Domain string `json:"domain"`
}

type GPUInfo struct {
	ID       string `json:"id"`
	Vendor   string `json:"vendor"`
	Device   string `json:"device"`
	Contract uint64 `json:"contract"`
}

type Workload struct {
	// Version is version of reservation object. On deployment creation, version must be 0
	// then only workloads that need to be updated must match the version of the deployment object.
	// if a deployment update message is sent to a node it does the following:
	// - validate deployment version
	// - check workloads list, if a version is not matching the new deployment version, the workload is untouched
	// - if a workload version is same as deployment, the workload is "updated"
	// - if a workload is removed, the workload is deleted.
	Version uint32 `json:"version"`
	//Name is unique workload name per deployment  (required)
	Name string `json:"name"`
	// Type of the reservation (container, zdb, vm, etc...)
	Type string `json:"type"`
	// Data is the reservation type arguments.
	Data json.RawMessage `json:"data"`
	// Metadata is user specific meta attached to deployment, can be used to link this
	// deployment to other external systems for automation
	Metadata string `json:"metadata"`
	//Description human readale description of the workload
	Description string `json:"description"`
	// Result of reservation, set by the node
	Result Result `json:"result"`
}

type Result struct {
	// Time when the result is sent
	Created int64 `json:"created"`
	// State of the deployment (ok,error)
	State string `json:"state"`
	// if State is "error", then this field contains the error
	// otherwise it's nil
	Error string `json:"message"`
	// Data is the information generated by the provisioning of the workload
	// its type depend on the reservation type
	Data json.RawMessage `json:"data"`
}

type Deployment struct {
	// Version must be set to 0 on deployment creation. And then it has to
	// be incremented with each call to update.
	Version uint32 `json:"version"`
	// TwinID is the id of the twin sendign the deployment. A twin then can only
	// `get` status about deployments he owns.
	TwinID uint32 `json:"twin_id"`
	// ContractID the contract must be "pre created" on substrate before the deployment is
	// sent to the node. The node will then validate that this deployment hash, will match the
	// hash attached to this contract.
	// the flow should go as follows:
	// - fill in ALL deployment details (metadata, and workloads)
	// - calculate the deployment hash (by calling ChallengeHash method)
	// - create the contract with the right hash
	// - set the contract id on the deployment object
	// - send deployment to node.
	ContractID uint64 `json:"contract_id"`
	// Metadata is user specific meta attached to deployment, can be used to link this
	// deployment to other external systems for automation
	Metadata string `json:"metadata"`
	// Description is human readable description of the deployment
	Description string `json:"description"`
	// Expiration [deprecated] is not used
	Expiration int64 `json:"expiration"`
	// SignatureRequirement specifications
	SignatureRequirement SignatureRequirement `json:"signature_requirement"`
	// Workloads is a list of workloads associated with this deployment
	Workloads []Workload `json:"workloads"`
}

type SignatureRequirement struct {
	Requests       []SignatureRequest `json:"requests"`
	WeightRequired uint               `json:"weight_required"`
	Signatures     []Signature        `json:"signatures"`
	SignatureStyle string             `json:"signature_style"`
}
type SignatureRequest struct {
	TwinID   uint32 `json:"twin_id"`
	Required bool   `json:"required"`
	Weight   uint   `json:"weight"`
}

type Signature struct {
	TwinID        uint32 `json:"twin_id"`
	Signature     string `json:"signature"`
	SignatureType string `json:"signature_type"`
}

type ExitDevice struct {
	// IsSingle is set to true if br-pub
	// is connected to zos bridge
	IsSingle bool `json:"is_single"`
	// IsDual is set to true if br-pub is
	// connected to a physical nic
	IsDual bool `json:"is_dual"`
	// AsDualInterface is set to the physical
	// interface name if IsDual is true
	AsDualInterface string `json:"dual_interface"`
}

type Interface struct {
	Name string
	IPs  []string `json:"ips"`
	Mac  string   `json:"mac"`
}
