@startuml

title 0-OS upgrade flow

:download upgrade flist;
partition "Atomic Upgrade" {
    floating note right: If any of these steps fail, rollback is executed
    :execute pre-copy;
    :create copy of current data;
    :create copy of current modules;
    :copy new file into cache;
    :execute post-copy;
    :stop services;
    :call migrate on current data;
    :start services;
    :call post-start;
}
if (atomic upgrade applied?) then (yes)
  :upgrade done;
  stop
else (no)
  :rollback data;
  :rollback modules;
  :blacklist upgrade ID;
  note right: prevent this upgrade to be applied again
  :start services;
  if (service started?) then (yes)
   :log failure;
    stop
  else (no)
    :notify owner system is not healthy anymore;
    stop
  endif
endif

@enduml