name: Zos Update Worker

defaults:
  run:
    working-directory: tools/zos-update-worker 

on: 
  push:
    paths:
      - tools/zos-update-worker/**
  pull_request:
    paths:
      - tools/zos-update-worker/**

jobs:
  Explore-Packge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install GO
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.6
          args: --timeout 3m --verbose
          working-directory: tools/zos-update-worker

      - name: staticcheck
        uses: dominikh/staticcheck-action@v1.4.0
        with:
          version: "2025.1.1"
          working-directory: tools/zos-update-worker
        env:
          GO111MODULE: on

      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-flags: "-l -d"
          gofmt-path: "tools/zos-update-worker"
       
      - name: Test
        run: go test -v ./...
  

